stages:
  - prepare
  - build
  - upload
  - release

prepare:
  stage: prepare
  image: rust
  rules:
    - if: $CI_COMMIT_TAG
      when: never # Do not run this job when a tag is created manually
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH # Run this job when commits are pushed or merged to the default branch
  script:
    - echo "======== PREPARE ========"
    - echo "PKG_VERSION=$(awk -F ' = ' '$1 ~ /version/ { gsub(/["]/, "", $2); printf("%s",$2) }' Cargo.toml)" >> variables.env
    - echo "PKG_REGISTRY_URL=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic" >> variables.env
    - echo $PKG_VERSION
  artifacts:
    reports:
      dotenv: variables.env


tests:
  stage: test
  image: rust
  script:
    - echo "======== TESTS JOB ========"
    - apt update
    - apt install lld clang -y
    - cargo test

build:
  stage: build
  image: ubuntu:24.04
  needs:
    - job: test
    - job: prepare
      artifacts: true
  script:
    - echo "======== BUILD ========"
    - apt update
    - apt install lld clang curl -y
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - source "$HOME/.cargo/env"
    - cargo build --release
    - mkdir bin
    - mv target/release/capture_tls_handshake bin/capture_tls_handshake-v${PKG_VERSION}
    - ls -la bin/
  artifacts:
    paths:
      - bin/


upload:
  stage: upload
  image: curlimages/curl:latest
  needs:
    - job: prepare
      artifacts: true
    - job: build
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
      when: never # Do not run this job when a tag is created manually
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH # Run this job when commits are pushed or merged to the default branch
  script:
    - echo "======== UPLOAD JOB ========"
    - ls -la bin/
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file bin/capture-tls-handshakes-v${PKG_VERSION} ${PKG_REGISTRY_URL}/x86_64-unknown-linux-gnu/v${PKG_VERSION}/capture-tls-handshakes'


release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: prepare
      artifacts: true
    - job: build
  rules:
    - if: $CI_COMMIT_TAG
      when: never # Do not run this job when a tag is created manually
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH # Run this job when commits are pushed or merged to the default branch
  script:
    - echo "======== RELEASE JOB ========"
  release: 
    tag_name: "v$PKG_VERSION" 
    description: "Capture TLS Handshake v$PKG_VERSION"
    ref: "$CI_COMMIT_SHA" # The tag is created from the pipeline SHA.
    assets:
      links:
        - name: "v$PKG_VERSION"
          url: "${PKG_REGISTRY_URL}/x86_64-unknown-linux-gnu/v${PKG_VERSION}/capture-tls-handshakes"
